# Generated by Django 4.2.1 on 2023-05-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('protein', models.IntegerField(verbose_name='Белки')),
                ('fats', models.IntegerField(verbose_name='Жиры')),
                ('carbon', models.IntegerField(verbose_name='Углеводы')),
                ('calories', models.IntegerField(verbose_name='Ккал')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('orderComposition', models.TextField(verbose_name='Состав заказа')),
                ('time', models.DateTimeField(verbose_name='Время заказа')),
                ('status', models.CharField(max_length=10, verbose_name='Статус заказа')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.client')),
            ],
        ),
    ]
