# Generated by Django 4.2.1 on 2023-05-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_client_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиента', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Пиццу', 'verbose_name_plural': 'Пиццы'},
        ),
        migrations.AddField(
            model_name='pizza',
            name='cost',
            field=models.IntegerField(default=None, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=None, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default=None, max_length=10, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='calories',
            field=models.IntegerField(default=None, verbose_name='Ккал'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='carbon',
            field=models.IntegerField(default=None, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='fats',
            field=models.IntegerField(default=None, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='protein',
            field=models.IntegerField(default=None, verbose_name='Белки'),
        ),
    ]
