# Generated by Django 4.2.1 on 2023-05-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_client_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
