# Generated by Django 4.2.1 on 2023-05-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_delete_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('cost', models.IntegerField(default=None, verbose_name='Стоимость')),
                ('protein', models.IntegerField(default=None, verbose_name='Белки')),
                ('fats', models.IntegerField(default=None, verbose_name='Жиры')),
                ('carbon', models.IntegerField(default=None, verbose_name='Углеводы')),
                ('calories', models.IntegerField(default=None, verbose_name='Ккал')),
            ],
            options={
                'verbose_name': 'Пиццу',
                'verbose_name_plural': 'Пиццы',
            },
        ),
    ]
