# Generated by Django 4.2.1 on 2023-05-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='img',
            field=models.TextField(default=None, max_length=50, verbose_name='Имя картинки'),
        ),
    ]
