# Generated by Django 4.2.1 on 2023-05-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_pizza_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
