# Generated by Django 4.2.1 on 2023-05-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='city',
            field=models.CharField(default=None, max_length=20, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='sale',
            field=models.BooleanField(default=None, verbose_name='По скидке?'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='img',
            field=models.ImageField(default='static/catalog/img/bg.jpg', upload_to='catalog/static/catalog/img/pizzas', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='tittle',
            field=models.CharField(default=None, max_length=20, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.category'),
        ),
    ]
