# Generated by Django 4.2.1 on 2023-05-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_category_pizza_city_pizza_sale_alter_pizza_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='category',
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.ManyToManyField(to='catalog.category'),
        ),
    ]
