# Generated by Django 5.2.5 on 2025-08-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_category_options_remove_pizza_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='По скидке?'),
        ),
    ]
