# Generated by Django 5.2.5 on 2025-08-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_pizza_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='calories',
            field=models.FloatField(blank=True, null=True, verbose_name='Ккал'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='carbon',
            field=models.FloatField(blank=True, null=True, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='fats',
            field=models.FloatField(blank=True, null=True, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='Белки'),
        ),
    ]
